---
apiVersion: v1
kind: replicationcontroller
metadata:
 name: httpd-rc 
 labels:
  author: intelliqit
spec:
 replicas: 3
 templicas:
  metadata:
   name: httpd-pod
   labels:
    author: intelliqit
  spec: 
   containers:
    - name: myhttpd
      image: httpd
      ports:
       - containerPort: 80
         hostPort: 8080

...
